# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        apt update -y
        apt install -y curl
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test API
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"subject": "test 1","data": "this is a test"}'
